apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-pvc
  labels:
    app: hdfs
    role: namenode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
