apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs
    role: namenode
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: hdfs
    role: namenode
  type: ClusterIP
