apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs
    role: namenode
spec:
  ports:
    - name: rpc
      port: 9000
      targetPort: 9000
    - name: http
      port: 9870
      targetPort: 9870
  selector:
    app: hdfs
    role: namenode
  type: ClusterIP
