apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-1
  labels:
    app: hdfs
    role: datanode
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/hadoop/1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
  labels:
    app: hdfs
    role: namenode
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/hadoop/namenode"
