apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/hadoop/1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/hadoop/2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/hadoop/namenode"
