apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-resourcemanager
  labels:
    app: hdfs
    role: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs
      role: resourcemanager
  template:
    metadata:
      labels:
        app: hdfs
        role: resourcemanager
    spec:
      automountServiceAccountToken: false
      containers:
        - name: resourcemanager
          image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 8088
          env:
            - name: SERVICE_PRECONDITION
              value: "hdfs-namenode:9000 hdfs-namenode:9870 hdfs-datanode:50010"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
